#!/usr/bin/env bun
/**
 * 把 popup/options 内部硬编码字符串合并到 overlay.ts(只追加不重复)
 *
 * 用法:
 *   bun run tools/merge-popup-strings.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const OVERLAY_TS = join(ROOT, "src", "extension", "utils", "i18n", "overlay.ts");

// 仅 POPUP_INNER 用到的字符串,不与已有 OVERLAY_DICT 重复
const POPUP_INNER: Array<[string, string]> = [
	["FULL", "已满"],
	["Resets in", "恢复于"],
	["Landing in", "落地于"],
	["Full in", "将于"],
	["Cooldown over in", "冷却将于"],
	["No bar data available.", "暂无状态条数据。"],
	["Traveling", "旅行中"],
	["Cooldowns", "冷却中"],
	["No cooldowns active.", "暂无冷却。"],
	["Overview", "概览"],
	["No stakeouts added.", "未添加监视目标。"],
	["No faction stakeouts.", "暂无帮派监视。"],
	["Add Stakeout", "添加监视"],
	["Remove Stakeout", "移除监视"],
	["Last seen:", "最后出现:"],
	["Notes:", "备注:"],
	["Note:", "备注:"],
	["Life:", "生命值:"],
	["Energy:", "能量:"],
	["Nerve:", "勇气:"],
	["Happy:", "幸福度:"],
	["Chain:", "连击:"],
	["Merits:", "功勋点:"],
	["Income:", "收入:"],
	["Rank:", "段位:"],
	["Job:", "工作:"],
	["Leader:", "帮主:"],
	["Co-leader:", "副帮主:"],
	["Members:", "帮众:"],
	["Territories:", "领土:"],
	["Treaties:", "协定:"],
	["Buy price:", "买入价:"],
	["Sell price:", "卖出价:"],
	["Market price:", "市场价:"],
	["Stock price:", "股价:"],
	["Total cost:", "总费用:"],
	["Total value:", "总价值:"],
	["Net worth:", "净资产:"],
	["Stock net worth:", "股票净资产:"],
	["Item net worth:", "物品净资产:"],
	["Bank net worth:", "银行净资产:"],
	["Cash net worth:", "现金净资产:"],
	["Total net worth:", "总净资产:"],
	["Level:", "等级:"],
	["Age:", "年龄:"],
	["Status:", "状态:"],
	["Last action:", "最后动作:"],
	["User ID:", "用户 ID:"],
	["Username:", "用户名:"],
	["Faction:", "帮派:"],
	["Company:", "公司:"],
	["Profile:", "个人资料:"],
	["Donator:", "捐赠者:"],
	["Active:", "激活:"],
	["Inactive:", "未激活:"],
	["Online:", "在线:"],
	["Offline:", "离线:"],
	["Online now", "当前在线"],
	["Online (Idle)", "在线(挂机)"],
	["Online (Active)", "在线(活跃)"],
	["last seen", "最后出现"],
	["ago", "前"],
	["ID:", "ID:"],
	["XP:", "经验:"],
	["EXP:", "经验:"],
	["Time:", "时间:"],
	["Date:", "日期:"],
	["Price:", "价格:"],
	["Quantity:", "数量:"],
	["Amount:", "数量:"],
	["Total:", "总计:"],
	["Bonus:", "加成:"],
	["Reward:", "奖励:"],
	["Cost:", "费用:"],
	["Fees:", "手续费:"],
	["Fee:", "手续费:"],
	["Duration:", "持续时间:"],
	["Cooldown:", "冷却:"],
	["Time left:", "剩余时间:"],
	["Time remaining:", "剩余时间:"],
	["Ready in:", "就绪于:"],
	["Ready at:", "就绪于:"],
	["Ready", "就绪"],
	["Open in new tab", "在新标签页打开"],
	["Open Torn", "打开 Torn"],
	["Open Wiki", "打开 Wiki"],
	["Refresh data", "刷新数据"],
	["Refresh data.", "刷新数据。"],
	["Refresh now", "立即刷新"],
	["Last updated:", "最后更新:"],
	["Last updated", "最后更新"],
	["Updated:", "更新于:"],
	["Last sync:", "最后同步:"],
	["Never updated", "从未更新"],
	["Auto-refresh", "自动刷新"],
	["Auto-update", "自动更新"],
	["Manual refresh", "手动刷新"],
	["Force refresh", "强制刷新"],
	["Force reload", "强制重载"],
	["Database", "数据库"],
	["Database size", "数据库大小"],
	["Database version", "数据库版本"],
	["Storage used", "已用存储"],
	["Storage limit", "存储上限"],
	["Cleared cache.", "已清空缓存。"],
	["Cache cleared.", "已清空缓存。"],
	["Reinitialized timers", "已重置定时器"],
	["Maintenance mode", "维护模式"],
	["Developer mode", "开发者模式"],
	["Debug mode", "调试模式"],
	["Verbose mode", "详细模式"],
	["Silent mode", "静默模式"],
	["Test mode", "测试模式"],
	["Experimental", "实验性"],
	["Beta", "测试版"],
	["Alpha", "内测版"],
	["Stable", "稳定版"],
	["Production", "生产"],
	["Development", "开发"],
	["Section", "标签"],
	["Group", "分组"],
	["Subpage", "子页面"],
	["Top bar", "顶部栏"],
	["Bottom bar", "底部栏"],
	["Header", "头部"],
	["Footer", "底部"],
	["Main content", "主内容"],
	["Sidebar items", "侧边栏项目"],
	["Custom links", "自定义链接"],
	["Add link", "添加链接"],
	["Remove link", "移除链接"],
	["Link name", "链接名称"],
	["Link URL", "链接 URL"],
	["Link target", "链接目标"],
	["_blank", "_blank(新窗口)"],
	["_self", "_self(当前窗口)"],
	["Drag to reorder", "拖拽以重新排序"],
	["Reset all", "全部重置"],
	["Reset section", "重置当前分组"],
	["Reset group", "重置当前组"],
	["Reset preferences", "重置偏好设置"],
	["Import data", "导入数据"],
	["Export data", "导出数据"],
	["Import from file", "从文件导入"],
	["Export to file", "导出到文件"],
	["Import from clipboard", "从剪贴板导入"],
	["Export to clipboard", "导出到剪贴板"],
	["Imported successfully", "导入成功"],
	["Exported successfully", "导出成功"],
	["Import failed", "导入失败"],
	["Export failed", "导出失败"],
	["Import error", "导入错误"],
	["Export error", "导出错误"],
	["Invalid data", "数据无效"],
	["Invalid data.", "数据无效。"],
	["Corrupted data", "数据已损坏"],
	["Corrupted data.", "数据已损坏。"],
	["Data is too large", "数据过大"],
	["Data is too large.", "数据过大。"],
	["Please try again", "请重试"],
	["Please try again.", "请重试。"],
	["Operation successful", "操作成功"],
	["Operation successful.", "操作成功。"],
	["Operation failed", "操作失败"],
	["Operation failed.", "操作失败。"],
	["Are you sure?", "确认操作?"],
	["Are you sure you want to do this?", "确认要进行此操作?"],
	["This action cannot be undone", "此操作无法撤销"],
	["This action cannot be undone.", "此操作无法撤销。"],
	["Confirm action", "确认操作"],
	["Cancel action", "取消操作"],
	["Proceed", "继续"],
	["Proceed anyway", "仍然继续"],
	["Confirmation", "确认"],
	["Confirmation Required", "需要确认"],
	["Confirm Action", "确认操作"],
	["Are you absolutely sure?", "你完全确定吗?"],
	["Type DELETE to confirm", "输入 DELETE 以确认"],
	["Delete confirmation", "删除确认"],
	["Confirm deletion", "确认删除"],
	["Confirm purchase", "确认购买"],
	["Confirm sale", "确认出售"],
	["Confirm trade", "确认交易"],
	["Confirm transfer", "确认转账"],
	["Confirm attack", "确认攻击"],
	["Confirm bust", "确认劫狱"],
	["Confirm bail", "确认保释"],
	["Confirm join", "确认加入"],
	["Confirm leave", "确认离开"],
	["Confirm donation", "确认捐赠"],
	["Confirm deposit", "确认存入"],
	["Confirm withdrawal", "确认提取"],
	["Confirm send", "确认发送"],
	["Confirm accept", "确认接受"],
	["Confirm decline", "确认拒绝"],
	["Required field", "必填项"],
	["Required", "必填"],
	["Optional", "可选"],
	["Field is required", "字段必填"],
	["Field is required.", "字段必填。"],
	["Invalid input", "输入无效"],
	["Invalid input.", "输入无效。"],
	["Please enter a valid value", "请输入有效值"],
	["Please enter a valid value.", "请输入有效值。"],
	["Value must be positive", "值必须为正"],
	["Value must be positive.", "值必须为正。"],
	["Value must be a number", "值必须为数字"],
	["Value must be a number.", "值必须为数字。"],
	["Value too large", "值过大"],
	["Value too small", "值过小"],
	["Out of range", "超出范围"],
	["Out of range.", "超出范围。"],
	["Total items", "总物品数"],
	["Total income", "总收入"],
	["Total spent", "总支出"],
	["Total earned", "总收入"],
	["Total kills", "总击杀"],
	["Total deaths", "总死亡"],
	["Total wins", "总胜利"],
	["Total losses", "总失败"],
	["Win rate", "胜率"],
	["Loss rate", "败率"],
	["Kill ratio", "击杀比"],
	["K/D ratio", "K/D 比"],
	["Average", "平均"],
	["Average damage", "平均伤害"],
	["Average cost", "平均费用"],
	["Average price", "平均价格"],
	["Average value", "平均值"],
	["Maximum", "最大"],
	["Maximum damage", "最大伤害"],
	["Maximum value", "最大值"],
	["Minimum", "最小"],
	["Minimum damage", "最小伤害"],
	["Minimum value", "最小值"],
	["Median", "中位数"],
	["Mode", "众数"],
	["Sum", "总和"],
	["Range", "范围"],
	["Percentile", "百分位"],
	["Top 1%", "前 1%"],
	["Top 5%", "前 5%"],
	["Top 10%", "前 10%"],
	["Top 25%", "前 25%"],
	["Top 50%", "前 50%"],
	["Bottom 50%", "后 50%"],
	["Time zone", "时区"],
	["Local time", "本地时间"],
	["Server time", "服务器时间"],
	["TCT", "Torn 城时间"],
	["TCT time", "Torn 城时间"],
	["Time until", "倒计时"],
	["Time since", "已过时间"],
	["Time elapsed", "已用时间"],
	["Remaining time", "剩余时间"],
	["Days left", "剩余天数"],
	["Hours left", "剩余小时"],
	["Minutes left", "剩余分钟"],
	["Seconds left", "剩余秒数"],
	["View profile", "查看资料"],
	["View faction", "查看帮派"],
	["View company", "查看公司"],
	["View on market", "在市场上查看"],
	["View in wiki", "在 Wiki 查看"],
	["More details", "更多详情"],
	["Less details", "收起详情"],
	["Full details", "完整详情"],
	["Brief details", "简要详情"],
	["Quick view", "快速查看"],
	["Detailed view", "详细查看"],
	["List view", "列表视图"],
	["Grid view", "网格视图"],
	["Table view", "表格视图"],
	["Compact view", "紧凑视图"],
	["Expand all", "全部展开"],
	["Collapse all", "全部折叠"],
	["Pin to top", "置顶"],
	["Pin to bottom", "置底"],
	["Unpin", "取消固定"],
	["Mark as read", "标记为已读"],
	["Mark as unread", "标记为未读"],
	["Mark all as read", "全部标记为已读"],
	["Mark all as unread", "全部标记为未读"],
	["Delete selected", "删除选中"],
	["Remove selected", "移除选中"],
	["Export selected", "导出选中"],
	["Import selected", "导入选中"],
];

function extractExistingKeys(tsContent: string): Set<string> {
	const set = new Set<string>();
	// 匹配双引号包裹的 key:"..." 或裸 key:"..."
	const re = /(?<![\w$])\s*(?:"([^"]+)"|([A-Za-z_][\w]*))\s*:\s*"/g;
	let m: RegExpExecArray | null;
	while ((m = re.exec(tsContent))) {
		set.add(m[1] ?? m[2]);
	}
	return set;
}

const ts = readFileSync(OVERLAY_TS, "utf8");
const existing = extractExistingKeys(ts);
const toAdd: Array<[string, string]> = [];
const seen = new Set<string>();
for (const [en, zh] of POPUP_INNER) {
	if (existing.has(en)) continue;
	if (seen.has(en)) continue;
	seen.add(en);
	toAdd.push([en, zh]);
}

console.log(`[merge-popup-strings] popup inner 总条目 ${POPUP_INNER.length}`);
console.log(`[merge-popup-strings] overlay.ts 现有 ${existing.size} 个 key`);
console.log(`[merge-popup-strings] 新增 ${toAdd.length} 个条目`);

if (toAdd.length === 0) {
	process.exit(0);
}

const blockLines = ["", "\t// ========== Popup / Options 内部硬编码字符串 =========="];
for (const [en, zh] of toAdd) {
	const keyNeedsQuote = /[\s\-_:&'/.,()]/.test(en);
	const key = keyNeedsQuote ? `"${en.replaceAll('"', '\\"')}"` : en;
	const value = zh.replaceAll('"', '\\"');
	blockLines.push(`\t${key}: "${value}",`);
}
const block = blockLines.join("\n");

const closingIdx = ts.lastIndexOf("};");
if (closingIdx === -1) {
	console.error("[merge-popup-strings] 未找到 overlay.ts 结束标记");
	process.exit(1);
}

const updated = ts.slice(0, closingIdx) + block + "\n" + ts.slice(closingIdx);
writeFileSync(OVERLAY_TS, updated, "utf8");
console.log(`[merge-popup-strings] 已写入 ${toAdd.length} 个新条目`);
